# paths:
path_to_data: '/home/otabek.nazarov/Downloads/hc701/hectooor/data/hecktor2021_train/hecktor_nii/hecktor_nii_resampled'  # directory with images
path_to_pkl: '/home/otabek.nazarov/Downloads/hc701/hectooor/neck-tumor-3D-segmentation/train_configs/new_splits/split_0.pkl'  # pkl file with train / val splits
path_to_save_dir: '/home/otabek.nazarov/Downloads/hc701/hectooor/neck-tumor-3D-segmentation/model_trainers/baseline_results'  # all results (weights, learning curves, etc) will be saved here

# train settings:
train_batch_size: 4
val_batch_size: 1
num_workers: 2 

lr: 1e-3  # Initial learning rate
n_epochs: 60 
n_cls: 2  # Background and tumor
in_channels: 2  # Number of input modalities (PET and CT)
n_filters: 16

T_0: 25  # Parameter for 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts'
eta_min: 1e-5  # Parameter for 'torch.optim.lr_scheduler.CosineAnnealingWarmRestarts'
